stages:
  - containerization
  - deployment

variables:
  DOCKER_IMAGE: 172.16.98.151:5000/kubernetes-deployment-example

containerization:
  stage: containerization
  script:
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}

deployment:
  stage: deployment
  script:
    - kubectl apply -f deployment.yaml
    - kubectl set image deployment/example-deployment example-container=${DOCKER_IMAGE}
  environment:
    name: staging
