stages:
  - containerization
  - deployment

variables:
  # DOCKER_IMAGE: 172.16.98.151:5000/kubernetes-deployment-example
  DOCKER_IMAGE: kubernetes-deployment-example
  DEPLOYMENT: example-deployment

before_script:
  - docker login -u $DOCKER_USERNAMR -p $DOCKER_PASSWORD

containerization:
  stage: containerization
  script:
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}
    - docker image rm ${DOCKER_IMAGE}

deployment:
  stage: deployment
  script:
    - kubectl apply -f deployment.yaml
    - kubectl rollout restart deployment/${DEPLOYMENT}
  environment:
    name: staging
