stages:
  - containerization
  - deployment

containerization:
  stage: containerization
  script:
    - docker build -t 192.168.179.5000/kubernetes-deployment-example:latest .
    - docker push 192.168.179.5000/kubernetes-deployment-example:latest

deployment:
  stage: deployment
  script:
    - kubectl apply -f deployment.yaml
  environment:
    name: staging
