apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: example-deployment
  template:
    metadata:
      labels:
        app: example-deployment
    spec:
      containers:
      - name: example
        image: 192.168.179.25:5000/kubernetes-deployment-example:8
        imagePullPolicy: Always
        ports:
        - containerPort: 12345
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: example-service
  name: example-service
spec:
  ports:
  - port: 12345
    nodePort: 30112
  selector:
    app: example-deployment
  type: LoadBalancer
